Presto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('PrestoApp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),

]

PrestoApp/urls.py
from django.urls import path
from . import views


urlpatterns  = [
    path('',views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name="post_edit"),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name="post_remove"),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('menu/',views.MenuListView.as_view(), name='menu'),
    path('menu/new/', views.CreateItemMenuView.as_view(), name='itemmenu'),
    path('menu/<int:pk>/remove/', views.MenuDeleteView.as_view(), name="menu_remove"),
    path('menu/<int:pk>/update/', views.MenuUpdateView.as_view(), name="menu_update"),
    path('kontakt/', views.kontakt, name='kontakt'),
    path('galeria/', views.galeria, name='galeria'),
]

PrestoApp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class CategoryMenu(models.Model):
    title = models.CharField(max_length=256)

    def __str__(self):
        return self.title

class ItemMenu(models.Model):
    category = models.ForeignKey(CategoryMenu, related_name='itemsmenu', on_delete=models.CASCADE)
    number = models.IntegerField()
    title = models.CharField(max_length=256)
    ingredients = models.CharField(max_length=1000)
    price1 = models.IntegerField()
    price2 = models.IntegerField(default=0)
    

    def get_absolute_url(self):
        return '/menu/'

    def __str__(self):
        return self.title

PrestoApp/forms.py
from django import forms
from PrestoApp.models import Post, ItemMenu


class PostForm(forms.ModelForm):

        class Meta():
            model = Post
            fields=('author','title','text')



class ItemMenuForm(forms.ModelForm):

        class Meta():
            model = ItemMenu
            fields=('category','number', 'title', 'ingredients', 'price1','price2')

PrestoApp/views.py
from django.shortcuts import render,get_object_or_404,redirect
from PrestoApp.models import Post, ItemMenu, CategoryMenu
from django.urls import reverse, reverse_lazy
from PrestoApp.forms import PostForm, ItemMenuForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
# Create your views here.


class PostListView(ListView):
    model = Post
    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post

class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'PrestoApp/post_detail.html'
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')

class DraftListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'PrestoApp/post_draft_list.html'
    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True)

class MenuListView(ListView):
    model = ItemMenu
    template_name = 'PrestoApp/menu.html'
    def get_queryset(self):
        return ItemMenu.objects.order_by('number')

class MenuUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    form_class = ItemMenuForm
    model = ItemMenu

class MenuDeleteView(LoginRequiredMixin, DeleteView):
    model = ItemMenu
    success_url = reverse_lazy('menu')

class CreateItemMenuView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    form_class = ItemMenuForm
    model = ItemMenu

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)

def kontakt(request):
    return render(request, 'PrestoApp/kontakt.html')

def galeria(request):
    return render(request, 'PrestoApp/galeria.html')

PrestoApp/templates/PrestoApp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Presto</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'CSS/prestostyle.css' %}">

    <body>

    <nav class= 'navbar navbar-light bg-light '>
      <div class="container">
        <ul class="nav navbar-nav navbar-collapse navbar-left">
          <li><a id="logo" class ='navbar-brand navbar-left bigbrand' href="{% url 'post_list' %}"><img src=" {% static 'IMAGES/logo.png' %} " alt=""></a></li>
          <li><a id="menu" href="{% url 'menu'%}">Menu</a></li>
          <li><a href="{% url 'galeria'%}">Galeria</a></li>
          <li><a href="{% url 'kontakt'%}">Kontakt</a></li>
        </ul>
        <ul class='nav navbar-nav navbar-right '>
            {%if user.is_authenticated%}
              <li><a href="{% url 'itemmenu'%}">Nowy item menu</a></li>
              <li><a href="{% url 'post_new'%}">Nowy Post</a></li>
              <li><a href="{% url 'post_draft_list'%}">Szkic postu</a></li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
              <li id="user">Witaj: {{user.username}}</li>
              {% else %}
              <li><a class='nav navbar-right' href="{% url 'login'%}"><span class= 'glyphicon glyphicon-user'></span></a></li>
              {%endif%}
        </ul>
      </div>
    </nav>

    <div class="bottomcontact">
      <p>Numer telefonu: 533 988 210</p>
    </div>

    <div class="content container">
            {% block content %}
            {% endblock %}
    </div>


  </body>
</html>

PrestoApp/templates/PrestoApp/galeria.html
{% extends "PrestoApp/base.html" %}
{% block content %}
{% load static %}
  <div class="gallery">
    <img src=" {% static 'IMAGES/IMG_1067.jpeg' %} " alt="" width="500" height="333">
    <img src=" {% static 'IMAGES/IMG_1068.jpeg' %} " alt="" width="500" height="333">
    <img src=" {% static 'IMAGES/IMG_1069.jpeg' %} " alt="" width="500" height="333">
    <img src=" {% static 'IMAGES/IMG_1070.jpeg' %} " alt="" width="500" height="333">
    <img src=" {% static 'IMAGES/IMG_1722.jpeg' %} " alt="" width="333" height="500">
    <img src=" {% static 'IMAGES/IMG_3223.jpeg' %} " alt="" width="333" height="500">
    <img src=" {% static 'IMAGES/IMG_4860.jpeg' %} " alt="" width="333" height="500">
    <img src=" {% static 'IMAGES/IMG_6084.jpeg' %} " alt="" width="333" height="500">
    <img src=" {% static 'IMAGES/IMG_7049.jpeg' %} " alt="" width="333" height="500">
    <img src=" {% static 'IMAGES/IMG_9249.jpeg' %} " alt="" width="333" height="500">
    <img src=" {% static 'IMAGES/IMG_9944.jpeg' %} " alt="" width="333" height="500">
  </div>

{% endblock %}

PrestoApp/templates/PrestoApp/itemmenu_confirm_delete.html
{% extends "PrestoApp/base.html" %}
{% block content %}
  <form method="POST">
    {% csrf_token %}
    <h1>Czy na pewno chcesz usunąć: {{object}} ?</h1>
    <input type="submit" class="btn btn-danger" value="Confirm">
  </form>
{% endblock %}

PrestoApp/templates/PrestoApp/itemmenu_form.html
{% extends "PrestoApp/base.html" %}
{% block content %}
<h1>Item Menu</h1>
<form class="itemmenu-form"  method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="save btn btn-default">Save</button>

</form>
{% endblock %}

PrestoApp/templates/PrestoApp/kontakt.html
{% extends "PrestoApp/base.html" %}
{% block content %}
<div class="container">
  <h1>Kontakt:</h1>

  <h2>Numer telefonu: 533 988 210</h2>
  <h2>Adres: Ostrów 35c</h2>
  <div class="mapouter"><div class="gmap_canvas"><iframe width=600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=Presto%20ostr%C3%B3w&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://123movies-to.org"></a><br><style>.mapouter{position:relative;text-align:right;height:500px;width:600px;}</style><a href="https://www.embedgooglemap.net">google map for web</a><style>.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}</style></div></div>
</div>

{% endblock %}

PrestoApp/templates/PrestoApp/menu.html
{% extends "PrestoApp/base.html" %}
{% block content %}

<div class="container menu">

<h2>Pizza:</h2>
<p class = "info">Do wyboru rodzaje ciasta: Cienkie lub Grube</p>
<table class="table">
  <td>Numer</td> <td>Nazwa</td> <td>Składniki</td><td class = "cena">Duża (32cm)</td> <td class = "cena">Maxi (50cm)</td>{%if user.is_authenticated%}<td>Edytuj / Usuń</td>{%endif%}
  {% for item in itemmenu_list %}
  {% if item.category.title == "Pizza" %}
   <tr>
     <td>{{item.number}}</td> <td>{{item.title}}</td> <td>{{item.ingredients}}</td> <td class = "cena">{{item.price1}} zł</td> <td class = "cena">{{item.price2}} zł</td>
     {%if user.is_authenticated%}
     <td><a class = 'btn btn-warning glyphicon glyphicon-wrench' href="{% url 'menu_update' pk=item.pk%}"></a>
     <a class = 'btn btn-danger glyphicon glyphicon-remove' href="{% url 'menu_remove' pk=item.pk%}"></a></td>
   {%endif%}
   </tr>
   {%endif%}
   {% endfor %}
</table>

<h2>Pizza Bambini:</h2>
<table class="table">
  <p class = "info">Pizza 20cm + frytki 100g + upominek</p>
  <td>Numer</td> <td>Nazwa</td> <td>Składniki</td><td class = "cena">Cena</td>{%if user.is_authenticated%}<td>Edytuj / Usuń</td>{%endif%}
  {% for item in itemmenu_list %}
  {% if item.category.title == "Pizza Bambini" %}
   <tr>
     <td>{{item.number}}</td> <td>{{item.title}}</td> <td>{{item.ingredients}}</td> <td class = "cena">{{item.price1}} zł</td>
     {%if user.is_authenticated%}
     <td><a class = 'btn btn-warning glyphicon glyphicon-wrench' href="{% url 'menu_update' pk=item.pk%}"></a>
     <a class = 'btn btn-danger glyphicon glyphicon-remove' href="{% url 'menu_remove' pk=item.pk%}"></a></td>
   {%endif%}
   </tr>
   {%endif%}
   {% endfor %}
</table>

<h2>Sałatki:</h2>
<table class="table">
  <td>Numer</td> <td>Nazwa</td> <td>Składniki</td><td class = "cena">Cena</td>{%if user.is_authenticated%}<td>Edytuj / Usuń</td>{%endif%}
  {% for item in itemmenu_list %}
  {% if item.category.title == "Sałatki" %}
   <tr>
     <td>{{item.number}}</td> <td>{{item.title}}</td> <td>{{item.ingredients}}</td> <td class = "cena">{{item.price1}} zł</td>
     {%if user.is_authenticated%}
     <td><a class = 'btn btn-warning glyphicon glyphicon-wrench' href="{% url 'menu_update' pk=item.pk%}"></a>
     <a class = 'btn btn-danger glyphicon glyphicon-remove' href="{% url 'menu_remove' pk=item.pk%}"></a></td>
   {%endif%}
   </tr>
   {%endif%}
   {% endfor %}
</table>

<h2>Dania Gorące:</h2>
<p class = "info">Przy zestawie do wyboru: frytki, ćwiartki ziemniaczane, kulki ziemniaczane</p>
<table class="table">
  <td>Numer</td> <td>Nazwa</td><td class = "cena">Cena</td>{%if user.is_authenticated%}<td>Edytuj / Usuń</td>{%endif%}
  {% for item in itemmenu_list %}
  {% if item.category.title == "Dania Gorące" %}
   <tr>
     <td>{{item.number}}</td> <td>{{item.title}}</td> <td class = "cena">{{item.price1}} zł</td>
     {%if user.is_authenticated%}
     <td><a class = 'btn btn-warning glyphicon glyphicon-wrench' href="{% url 'menu_update' pk=item.pk%}"></a>
     <a class = 'btn btn-danger glyphicon glyphicon-remove' href="{% url 'menu_remove' pk=item.pk%}"></a></td>
     {%endif%}
   </tr>
   {%endif%}
   {% endfor %}
</table>

<h2>Dania Barowe:</h2>
<table class="table">
  <td>Numer</td> <td>Nazwa</td><td class = "cena">Cena</td>{%if user.is_authenticated%}<td>Edytuj / Usuń</td>{%endif%}
  {% for item in itemmenu_list %}
  {% if item.category.title == "Dania Barowe" %}
   <tr>
     <td>{{item.number}}</td> <td>{{item.title}}</td> <td class = "cena">{{item.price1}} zł</td>
     {%if user.is_authenticated%}
     <td><a class = 'btn btn-warning glyphicon glyphicon-wrench' href="{% url 'menu_update' pk=item.pk%}"></a>
     <a class = 'btn btn-danger glyphicon glyphicon-remove' href="{% url 'menu_remove' pk=item.pk%}"></a></td>
     {%endif%}
   </tr>
   {%endif%}
   {% endfor %}
</table>

<h2>Dodatki:</h2>
<table class="table">
  <td>Nazwa</td> <td class = "cena">Cena</td> <td class = "cena">Cena przy MAXI</td>{%if user.is_authenticated%}<td>Edytuj / Usuń</td>{%endif%}
  {% for item in itemmenu_list %}
  {% if item.category.title == "Dodatki" %}
   <tr>
    <td>{{item.title}}</td> <td class = "cena">{{item.price1}} zł</td> <td class = "cena">{{item.price2}} zł</td>
    {%if user.is_authenticated%}
    <td><a class = 'btn btn-warning glyphicon glyphicon-wrench' href="{% url 'menu_update' pk=item.pk%}"></a>
    <a class = 'btn btn-danger glyphicon glyphicon-remove' href="{% url 'menu_remove' pk=item.pk%}"></a></td>
    {%endif%}
   </tr>
   {%endif%}
   {% endfor %}
</table>

<p class = "info">Zamówienia przyjmowane są do godz. 21:45.</p>
<p class = "info">Dowóz do 6km GRATIS! Powyżej 6km - 1km = 2,00zł.</p>
<p class = "info">Dowozy realizujemy tylko przy zamówieniu powyżej 30zł.</p>
<p class = "info">Oferta ważna od 1 sierpnia 2021r.</p>
{% endblock%}

PrestoApp/templates/PrestoApp/post_confirm_delete.html
{% extends "PrestoApp/base.html" %}
{% block content %}
  <form method="POST">
    {% csrf_token %}
    <h1>Czy na pewno usunąć: {{object}} ?</h1>
    <input type="submit" class="btn btn-danger" value="Confirm">
  </form>
{% endblock %}

PrestoApp/templates/PrestoApp/post_detail.html
{% extends "PrestoApp/base.html" %}
{% block content %}

  <h1 class="posttitle loader">{{post.title}}</h1>
  {% if post.published_date %}
    <div class="date postdate">
      {{post.published_date}}

    </div>
  {% else %}
    <a class = 'btn btn-primary' href="{% url 'post_publish' pk=post.pk%}">Opublikuj</a>
  {% endif %}

    <p class= 'postcontent jumbotron'> {{post.text|safe|linebreaksbr}}</p>
    {% if user.is_authenticated%}
      <a class = 'btn btn-primary' href="{% url 'post_edit' pk=post.pk%}">
      <span class='glyphicon glyphicon-pencil'></span>
    </a>
    <a class = 'btn btn-primary' href="{% url 'post_remove' pk=post.pk%}">
    <span class='glyphicon glyphicon-remove'></span>
  </a>
    {% endif %}
{% endblock %}

PrestoApp/templates/PrestoApp/post_draft_list.html
{% extends "PrestoApp/base.html" %}
{% block content %}
<h1>Szkice:</h1>
  {%for post in post_list %}
  <div class="post">
    <p class="date">Utworzone: {{post.create_date}}</p>
    <h1><a href="{% url 'post_detail' pk=post.pk%}">{{post.title}}</a></h1>
    <p>{{post.text|truncatechars:200}}</p>
  </div>
  {% endfor %}
{% endblock %}

PrestoApp/templates/PrestoApp/post_form.html
{% extends "PrestoApp/base.html" %}
{% block content %}
<h1>Post</h1>
<form class="post-form"  method="POST">
  {% csrf_token %}
  {{form.as_p|linebreaksbr}}
  <button type="submit" class="save btn btn-default">Zapisz</button>

</form>
{% endblock %}

PrestoApp/templates/PrestoApp/post_list.html
{% extends "PrestoApp/base.html" %}
{% block content %}
<div>
  {% for post in post_list %}


    <div class="post">
      <div class="date">
        <p>Dodany dnia: {{post.published_date|date:"d/m/Y G:i"}}</p>
      </div>
      <div class="posttitle jumbotron">
        <h2>{{post.title}}</h2>
        <p class="post">{{post.text|linebreaksbr}}</p>
      </div>
      {%if user.is_authenticated%}
      <td><a class = 'btn btn-warning glyphicon glyphicon-wrench' href="{% url 'post_edit' pk=post.pk%}"></a>
      <a class = 'btn btn-danger glyphicon glyphicon-remove' href="{% url 'post_remove' pk=post.pk%}"></a></td>
      {%endif%}
    </div>


  {% endfor %}
</div>
{% endblock %}